---

- name: restart avahi-aliases
  service: name=avahi-aliases state=restarted enabled=yes
  sudo: yes

- name: rebuild dnsmasq
  sudo: yes
  shell: docker-gen -notify="/etc/init.d/dnsmasq force-reload" /etc/templates/dockerhosts.tmpl /etc/dockerhosts

- name: rebuild nginx
  notify: restart nginx
  shell: docker-gen /etc/templates/nginx.tmpl /etc/nginx/sites-enabled/default
  sudo: yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  sudo: yes

- name: reload sshd
  service: name=ssh state=reloaded
  sudo: yes

- name: update issue
  shell: MODE=start /etc/network/if-up.d/show-ip-address
