---

- name: restart avahi-aliases
  service: name=avahi-aliases state=restarted enabled=yes
  sudo: yes

- name: restart docker-gen-dnsmasq
  service: name=docker-gen-dnsmasq state=restarted enabled=yes
  sudo: yes

- name: restart docker-gen-nginx
  service: name=docker-gen-nginx state=restarted enabled=yes
  sudo: yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  sudo: yes

- name: reload sshd
  service: name=ssh state=reloaded
  sudo: yes

- name: update issue
  shell: MODE=start /etc/network/if-up.d/show-ip-address
