---
- name: create hub folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ hub.app_dir }}"
    - "{{ hub.app_dir }}/pgdata"
    - "{{ hub.app_dir }}/config"
    - "{{ hub.app_dir }}/log"

- name: create hub env file for docker compose
  template: src=docker-env.j2 dest={{ hub.app_dir }}/.docker-env

- name: register hub in guisso
  command: docker-compose run --rm -T web rake apps:create[hub,hub-local.instedd.org,trusted] chdir={{ guisso.app_dir }}
  register: hub_guisso
  when: hub.guisso.enabled

- name: create hub config files
  template: src={{ item }}.j2 dest={{ hub.app_dir }}/config/{{item}}
  with_items:
    - guisso.yml
    - poirot.yml
    - settings.yml
    - secrets.yml

- name: create hub database config file
  copy: src=database.yml dest={{ hub.app_dir }}/config/database.yml

- name: create hub docker compose file
  template: src=docker-compose.yml.j2 dest={{ hub.app_dir }}/docker-compose.yml
  register: compose_file

- name: docker compose up databases
  command: docker-compose up -d db redis chdir={{ hub.app_dir }}

- name: migrate database
  command: docker-compose run --rm -T web bash /app/migrate chdir={{ hub.app_dir }}

- name: docker compose up application
  command: docker-compose up --force-recreate -d chdir={{ hub.app_dir }}
