- hosts: all
  roles:
    - ansible-pull
    - network
    - guisso
    - hub
    - nuntium
    - theme
    - pollit
  vars:
    avahi_hostname: instedd
    avahi_aliases:
      - pollit.instedd
      - login.instedd
      - nuntium.instedd
      - hub.instedd
      - theme.instedd
    local:
      hostname: instedd
      domainname: local
    pollit:
      hostname: pollit.instedd
      domainname: local
    guisso:
      hostname: login.instedd
      domainname: local
    nuntium:
      hostname: nuntium.instedd
      domainname: local
    hub:
      hostname: hub.instedd
      domainname: local


