- hosts: all
  roles:
    - ansible-pull
    - network
    - mysql
    - guisso
    - nuntium
    - theme
    - ask
    - asterisk
    - verboice
  vars:
    avahi_hostname: instedd
    avahi_aliases:
      - login.instedd
      - nuntium.instedd
      - theme.instedd
      - ask.instedd
      - verboice.instedd
      - verboice-broker.instedd
      - avahi.instedd
    local:
      domainname: local
