- hosts: all
  roles:
    # - ansible-pull
    # - network
    - mysql
    - guisso
    - hub
    - nuntium
    - theme
  vars:
    avahi_hostname: instedd
    avahi_aliases:
      - login.instedd
      - nuntium.instedd
      - hub.instedd
      - theme.instedd
    local:
      domainname: local
