- hosts: all
  roles:
    - ansible-pull
    - network
    - guisso
    - hub
    - nuntium
    - theme
    - pollit
  vars:
    avahi_hostname: instedd
    avahi_aliases:
      - pollit.instedd
      - login.instedd
      - nuntium.instedd
      - hub.instedd
      - theme.instedd
    local:
      domainname: local
