---
nuntium:
  version: 1.5
  hostname: "{{ local.hostname | default('nuntium') }}"
  domainname: "{{ local.domainname | default('local') }}"
  app_dir: /u/apps/nuntium

  amqp:
    user: nuntium
    pass: nuntium
    vhost: /nuntium

  guisso:
    enabled: true
    url: "{{ guisso.hostname | asurl(guisso.domainname) }}"

rabbitmq:
  cookie: RABBITMQCOOKIE
