---

- name: install dnsmasq
  apt: name=dnsmasq=2.68-1ubuntu0.1 state=present

- name: create empty dockerhosts file
  file: path=/etc/dockerhosts state=touch

- name: add extra hosts file
  template: src=extrahosts.j2 dest=/etc/extrahosts

- name: config dnsmasq
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.d/dnsmasq.conf

- name: setup template for dnsmasq-gen
  copy: src=dockerhosts.tmpl dest=/etc/templates/

- name: register service for docker-gen
  copy: src=docker-gen-dnsmasq.conf dest=/etc/init/ mode=0644
  notify: restart docker-gen-dnsmasq
