---

- name: install nginx
  apt: name=nginx=1.4.6-1ubuntu3.3 state=present

- name: setup template for nginx conf
  copy: src=nginx.tmpl dest=/etc/templates/
  changed_when: True
  notify: rebuild nginx
