---
- name: install mysql packages
  apt: name={{ item }} state=present
  with_items:
    - mysql-server-5.6
    - mysql-client-5.6
  register: install_mysql

- name: set root password
  command: /usr/bin/mysqladmin -u root password {{ mysql.root_password }}
  when: install_mysql.changed

- name: bind mysql to docker interface
  template: src=mysql.cnf.j2 dest=/etc/mysql/conf.d/bind.cnf owner=root mode=0644
  notify: restart mysql

- name: grant mysql privileges
  command: /usr/bin/mysql -u root --password={{ mysql.root_password }} -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'{{ item }}' IDENTIFIED BY '{{ mysql.root_password }}' WITH GRANT OPTION; FLUSH PRIVILEGES;"
  with_items:
    - "{{ ansible_eth0.ipv4.address }}"
    - "{{ ansible_docker0.ipv4.network }}/{{ ansible_docker0.ipv4.netmask }}"
