---
pollit:
  hostname: "{{ local.hostname | default('pollit') }}"
  version: "2.1.1"
  domainname: "{{ local.domainname | default('local') }}"
  app_dir: /u/apps/pollit

  guisso:
    enabled: true
    url: "{{ guisso.hostname | asurl(guisso.domainname) }}"

  hub:
    enabled: true
    url: "{{ hub.hostname | asurl(hub.domainname) }}"

  theme:
    url: "{{ theme.hostname | asurl(theme.domainname) | default('http://theme.instedd.org/') }}"

  nuntium:
    url: "{{ nuntium.hostname | asurl(nuntium.domainname) }}"
    account_name: pollit
    account_pass: pollit
    application: pollit
    pass: pollit
    interface_user: pollit
    interface_pass: pollit
