---

- name: add ansible repository
  apt_repository:
    repo: 'ppa:ansible/ansible'
    update_cache: yes

- name: install ansible
  apt: name=ansible=1.9.2-1ppa~trusty state=present

- name: setup hosts file in target machine
  copy: src=hosts dest=/etc/ansible/hosts

- name: setup ansible pull script for this repository
  template: src=pull.j2 dest=/usr/local/bin/instedd-upgrade mode=u=rwx,go=rx
