---
- name: add docker repository key
  apt_key: url="https://get.docker.io/gpg" id="A88D21E9"

- name: add docker repository
  apt_repository:
    repo: 'deb https://get.docker.io/ubuntu docker main'
    update_cache: yes

- name: install docker
  apt: name=lxc-docker={{ docker.package_version }} state=present

- name: configure logrotate
  copy: src=logrotate dest=/etc/logrotate.d/docker
