---
- name: check for docker-gen installation
  stat: path=/usr/local/bin/docker-gen
  register: dockergenst

- name: download docker-gen
  get_url: url=https://github.com/jwilder/docker-gen/releases/download/0.4.0/docker-gen-linux-amd64-0.4.0.tar.gz dest=/tmp/
  when: not dockergenst.stat.exists

- name: install docker-gen
  unarchive: src=/tmp/docker-gen-linux-amd64-0.4.0.tar.gz dest=/usr/local/bin/ copy=no
  when: not dockergenst.stat.exists

- name: setup templates dir
  file: state=directory path=/etc/templates/
