---
  - name: add docker repository key
    apt_key: url="https://get.docker.io/gpg" id="A88D21E9"

  - name: add docker repository
    apt_repository:
      repo: 'deb https://get.docker.io/ubuntu docker main'
      update_cache: yes

  - name: install docker
    apt: name=lxc-docker={{ docker.package_version }} state=present

  - name: get setuptools
    apt: name=python-setuptools state=present

  - name: make sure pip works
    shell: easy_install -U pip creates=/usr/local/bin/pip

  - name: upgrade distribute pip package due to issue with docker compose pip installation
    pip: name=distribute version=0.7.3

  - name: install docker-py
    pip: name=docker-py state=present version={{ docker.dockerpy_version }}

  - name: install docker-compose
    pip: name=docker-compose state=present version={{ docker.compose_version }}
