#!/bin/sh
if [ "$METHOD" = loopback ]; then
    exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
    exit 0
fi

echo -n "Ubuntu 14.04.2 LTS InSTEDD Box IP " > /etc/issue
/usr/local/bin/get-ip-address >> /etc/issue
echo "" >> /etc/issue
